// <auto-generated />
using System;
using Corretor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Corretor.Api.Migrations
{
    [DbContext(typeof(CorretorDbContext))]
    [Migration("20260713214057_AjustaDocumentoContratoExterno")]
    partial class AjustaDocumentoContratoExterno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Corretor.Api.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PessoaFisicaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PessoaJuridicaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("PessoaFisicaId");

                    b.HasIndex("PessoaJuridicaId");

                    b.ToTable("Cliente", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cliente_PessoaFisicaOuPessoaJuridica", "((`PessoaFisicaId` IS NOT NULL AND `PessoaJuridicaId` IS NULL) OR (`PessoaFisicaId` IS NULL AND `PessoaJuridicaId` IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("Corretor.Api.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("Contrato", (string)null);
                });

            modelBuilder.Entity("Corretor.Api.Entities.Dependente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PessoaFisicaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaFisicaId");

                    b.ToTable("Dependente", (string)null);
                });

            modelBuilder.Entity("Corretor.Api.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("longtext");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext");

                    b.Property<string>("CpfDependente")
                        .HasColumnType("longtext");

                    b.Property<string>("DataAprovacao")
                        .HasColumnType("longtext");

                    b.Property<string>("DataUpload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("DocumentoExternoId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("ExtracaoProcessada")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MotivoReprovacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoParentesco")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("Documento", (string)null);
                });

            modelBuilder.Entity("Corretor.Api.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Endereco", (string)null);
                });

            modelBuilder.Entity("Corretor.Api.Entities.FaixaEtaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Faixa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("FaixaEtaria", (string)null);
                });

            modelBuilder.Entity("Corretor.Api.Entities.Historico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("Historico", (string)null);
                });

            modelBuilder.Entity("Corretor.Api.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DataAprovacao")
                        .HasColumnType("longtext");

                    b.Property<string>("DataEnvio")
                        .HasColumnType("longtext");

                    b.Property<string>("DataRetorno")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Operadora")
                        .HasColumnType("longtext");

                    b.Property<int>("QuantidadeVidas")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WorkflowEtapa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Lead", (string)null);
                });

            modelBuilder.Entity("Corretor.Api.Entities.PessoaFisica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FaixaEtaria")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PessoaFisica", (string)null);
                });

            modelBuilder.Entity("Corretor.Api.Entities.PessoaJuridica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("IE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PessoaJuridica", (string)null);
                });

            modelBuilder.Entity("Corretor.Api.Entities.PosContrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("PosContrato", (string)null);
                });

            modelBuilder.Entity("Corretor.Api.Entities.Script", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Script", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Etapa = "CriacaoLead",
                            Mensagem = "Ola, recebi seu contato para cotacao de plano de saude. Vou confirmar alguns dados para encontrar as melhores opcoes.",
                            Tipo = "WhatsApp"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Etapa = "ConversaInicial",
                            Mensagem = "Voce procura plano individual, familiar ou empresarial? Tambem preciso saber cidade, operadora atual e se ha preferencia de rede.",
                            Tipo = "PerguntasIniciais"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            Etapa = "FaixaEtaria",
                            Mensagem = "Para calcular corretamente, me envie a quantidade de vidas por faixa etaria e informe quem sera titular e quem sera dependente.",
                            Tipo = "FaixaEtaria"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            Etapa = "EnvioSimulacao",
                            Mensagem = "Segue a simulacao com as opcoes de plano. Veja valores, rede, coparticipacao e cobertura antes de escolher a melhor alternativa.",
                            Tipo = "Envio"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            Etapa = "RetornoContato",
                            Mensagem = "Conseguiu avaliar a simulacao enviada? Posso te ajudar a comparar as opcoes e tirar duvidas sobre rede, carencia e valores.",
                            Tipo = "FollowUp"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            Etapa = "AprovacaoSimulacao",
                            Mensagem = "Perfeito, vamos seguir com a opcao escolhida. Vou iniciar a etapa de documentos para formalizar a proposta.",
                            Tipo = "Aprovacao"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            Etapa = "Documentacao",
                            Mensagem = "Envie os documentos do titular, dependentes ou empresa conforme o caso, incluindo identificacao e comprovante de endereco.",
                            Tipo = "Documentos"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            Etapa = "Contrato",
                            Mensagem = "A proposta esta pronta para assinatura. Confira os dados do contrato e me avise quando concluir para acompanharmos a implantacao.",
                            Tipo = "Assinatura"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            Etapa = "PosContrato",
                            Mensagem = "Contrato concluido. Vou acompanhar os proximos passos e te orientar sobre carteirinha, acesso ao aplicativo e uso do plano.",
                            Tipo = "BoasVindas"
                        });
                });

            modelBuilder.Entity("Corretor.Api.Entities.Simulacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Aprovada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DataEnvio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("Simulacao", (string)null);
                });

            modelBuilder.Entity("Corretor.Api.Entities.Cliente", b =>
                {
                    b.HasOne("Corretor.Api.Entities.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Corretor.Api.Entities.PessoaFisica", null)
                        .WithMany()
                        .HasForeignKey("PessoaFisicaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Corretor.Api.Entities.PessoaJuridica", null)
                        .WithMany()
                        .HasForeignKey("PessoaJuridicaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Corretor.Api.Entities.Contrato", b =>
                {
                    b.HasOne("Corretor.Api.Entities.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Corretor.Api.Entities.Dependente", b =>
                {
                    b.HasOne("Corretor.Api.Entities.PessoaFisica", null)
                        .WithMany()
                        .HasForeignKey("PessoaFisicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Corretor.Api.Entities.Documento", b =>
                {
                    b.HasOne("Corretor.Api.Entities.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Corretor.Api.Entities.Endereco", b =>
                {
                    b.HasOne("Corretor.Api.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Corretor.Api.Entities.FaixaEtaria", b =>
                {
                    b.HasOne("Corretor.Api.Entities.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Corretor.Api.Entities.Historico", b =>
                {
                    b.HasOne("Corretor.Api.Entities.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Corretor.Api.Entities.PosContrato", b =>
                {
                    b.HasOne("Corretor.Api.Entities.Contrato", null)
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Corretor.Api.Entities.Simulacao", b =>
                {
                    b.HasOne("Corretor.Api.Entities.Lead", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
